package Frames;

//Imports
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import Clases.*;
import java.sql.*;

/**
 *
 * @author Propietario
 */
public class VentanaDELETE extends javax.swing.JFrame {

    //Vars/Objs
    Conexion_BD_CAASA obclasecon=new Conexion_BD_CAASA();
    Connection con=obclasecon.conectar();
    
    /**
     * Creates new form VentanaDELETE
     */
    public VentanaDELETE() {
        initComponents();
        //Icono de la ventana------------------------
        ImageIcon icon=new ImageIcon("C:\\Users\\Propietario\\Desktop\\Trabajos - Semestre 8\\Gestión de Proyectos de Software\\NBP\\Sistema de operaciones CRUD CAASA\\src\\Imagenes\\lcaasa.jpg");
        this.setIconImage(icon.getImage());  
 
        //Elementos cboSeleccTabla----------------------
        cboSeleccTabla.addItem("...");
        cboSeleccTabla.addItem("Cliente");
        cboSeleccTabla.addItem("Domicilio");
        cboSeleccTabla.addItem("Automovil");
        cboSeleccTabla.addItem("Servicio");
        cboSeleccTabla.addItem("Asesor");
        cboSeleccTabla.setSelectedIndex(0);
        
        //Desactivar paneles y elementos------------------
        pnl_SeleccCampos.setEnabled(false);
        lbl_SeleccCampos.setEnabled(false);
        lbl_SeleccionCampos.setEnabled(false);
        lbl_SeleccionCampos2.setEnabled(false);
        cbo_Campos.setEnabled(false);
        
        pnl_IngresarDatos.setEnabled(false);
        lbl_IngresarVCampo.setEnabled(false);
        txtf_VCampoSelecc.setEnabled(false);
        btn_ELIMINAR.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnl_SeleccCampos = new javax.swing.JPanel();
        lbl_SeleccCampos = new javax.swing.JLabel();
        cbo_Campos = new javax.swing.JComboBox<>();
        lbl_SeleccionCampos = new javax.swing.JLabel();
        lbl_SeleccionCampos2 = new javax.swing.JLabel();
        pnl_IngresarDatos = new javax.swing.JPanel();
        lbl_IngresarVCampo = new javax.swing.JLabel();
        txtf_VCampoSelecc = new javax.swing.JTextField();
        btn_ELIMINAR = new javax.swing.JButton();
        cboSeleccTabla = new javax.swing.JComboBox<>();
        lbl_SeleccTabla = new javax.swing.JLabel();
        lbl_Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Eliminar registros");
        setResizable(false);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_SeleccCampos.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lbl_SeleccCampos.setText(">Elija un campo \"Primary Key\" o \"UNIQUE\" de la tabla:");

        cbo_Campos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_CamposActionPerformed(evt);
            }
        });

        lbl_SeleccionCampos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lbl_SeleccionCampos.setForeground(new java.awt.Color(0, 0, 153));
        lbl_SeleccionCampos.setText("SELECCIÓN:");

        lbl_SeleccionCampos2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 16)); // NOI18N
        lbl_SeleccionCampos2.setText("-");

        javax.swing.GroupLayout pnl_SeleccCamposLayout = new javax.swing.GroupLayout(pnl_SeleccCampos);
        pnl_SeleccCampos.setLayout(pnl_SeleccCamposLayout);
        pnl_SeleccCamposLayout.setHorizontalGroup(
            pnl_SeleccCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SeleccCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_SeleccCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_SeleccCamposLayout.createSequentialGroup()
                        .addComponent(lbl_SeleccCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(cbo_Campos, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_SeleccCamposLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_SeleccionCampos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_SeleccionCampos2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_SeleccCamposLayout.setVerticalGroup(
            pnl_SeleccCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_SeleccCamposLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_SeleccCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SeleccCampos)
                    .addComponent(cbo_Campos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(pnl_SeleccCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_SeleccionCampos)
                    .addComponent(lbl_SeleccionCampos2))
                .addContainerGap())
        );

        jPanel1.add(pnl_SeleccCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 970, 70));

        lbl_IngresarVCampo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        lbl_IngresarVCampo.setText(">Ingrese el valor del campo para localizar registro a eliminar:");

        txtf_VCampoSelecc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_VCampoSeleccActionPerformed(evt);
            }
        });

        btn_ELIMINAR.setBackground(new java.awt.Color(255, 51, 51));
        btn_ELIMINAR.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btn_ELIMINAR.setText("ELIMINAR");
        btn_ELIMINAR.setToolTipText("Insertar registro en la tabla seleccionada.");
        btn_ELIMINAR.setBorderPainted(false);
        btn_ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ELIMINARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_IngresarDatosLayout = new javax.swing.GroupLayout(pnl_IngresarDatos);
        pnl_IngresarDatos.setLayout(pnl_IngresarDatosLayout);
        pnl_IngresarDatosLayout.setHorizontalGroup(
            pnl_IngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_IngresarDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_IngresarVCampo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtf_VCampoSelecc, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(btn_ELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_IngresarDatosLayout.setVerticalGroup(
            pnl_IngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_IngresarDatosLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(pnl_IngresarDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_IngresarVCampo)
                    .addComponent(txtf_VCampoSelecc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        jPanel1.add(pnl_IngresarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 970, 100));

        cboSeleccTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSeleccTablaActionPerformed(evt);
            }
        });
        jPanel1.add(cboSeleccTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, 170, 30));

        lbl_SeleccTabla.setFont(new java.awt.Font("Malgun Gothic", 1, 20)); // NOI18N
        lbl_SeleccTabla.setText("•Seleccione la tabla en la que desea eliminar registros:");
        jPanel1.add(lbl_SeleccTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 30));

        lbl_Background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bck.png"))); // NOI18N
        jPanel1.add(lbl_Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1045, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1045, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ELIMINARActionPerformed
        //Variables 
        String valorCampo="";
        String cadena="   ";
        int id_beanasesor;
        long id_beanserv, nser_beanauto, id_beandom, id_beancli;
        //Condiciones de acuerdo a la tabla
        switch(cboSeleccTabla.getSelectedIndex()){
            case 0:
                break;
            case 1:
                //
                if(cbo_Campos.getSelectedIndex()==0){
                    valorCampo=txtf_VCampoSelecc.getText();
                    id_beancli=Long.parseLong(valorCampo);
                    BeanClient bcli_id=new BeanClient(id_beancli);
                    this.eliminarCliente(bcli_id);
                }else if(cbo_Campos.getSelectedIndex()==1){
                    valorCampo=txtf_VCampoSelecc.getText();
                    BeanClient bcli_rfc=new BeanClient(valorCampo,cadena);
                    this.eliminarCliente2(bcli_rfc);
                }else if(cbo_Campos.getSelectedIndex()==2){
                    valorCampo=txtf_VCampoSelecc.getText();
                    BeanClient bcli_curp=new BeanClient(cadena,valorCampo);
                    this.eliminarCliente3(bcli_curp);
                }
                break;
            case 2:
                //
                if(cbo_Campos.getSelectedIndex()==0){
                    valorCampo=txtf_VCampoSelecc.getText();
                    id_beandom=Long.parseLong(valorCampo);
                    BeanDomicilio bdom_id=new BeanDomicilio(id_beandom);
                    this.eliminarDomicilio(bdom_id);
                }
                break;
            case 3:
                //
                if(cbo_Campos.getSelectedIndex()==0){
                    valorCampo=txtf_VCampoSelecc.getText();
                    nser_beanauto=Long.parseLong(valorCampo);
                    BeanAuto bauto_nser=new BeanAuto(nser_beanauto);
                    this.eliminarAuto(bauto_nser);
                }
                break;
            case 4:
                //
                if(cbo_Campos.getSelectedIndex()==0){
                    valorCampo=txtf_VCampoSelecc.getText();
                    id_beanserv=Long.parseLong(valorCampo);
                    BeanServ bserv_id=new BeanServ(id_beanserv);
                    this.eliminarServicio(bserv_id);
                }
                break;
            case 5:
                //
                if(cbo_Campos.getSelectedIndex()==0){
                    valorCampo=txtf_VCampoSelecc.getText();
                    id_beanasesor=Integer.parseInt(valorCampo);
                    BeanAsesor basesor_id=new BeanAsesor(id_beanasesor);
                    this.eliminarAsesor(basesor_id); 
                }else if(cbo_Campos.getSelectedIndex()==1){
                    valorCampo=txtf_VCampoSelecc.getText();
                    BeanAsesor basesor_email=new BeanAsesor(valorCampo);
                    this.eliminarAsesor2(basesor_email);
                }
                break;
            default:
                break;
        }
    }//GEN-LAST:event_btn_ELIMINARActionPerformed
    
    private void cboSeleccTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSeleccTablaActionPerformed
        //Switch 
        switch(cboSeleccTabla.getSelectedIndex()){
            case 0:
                //
                cbo_Campos.removeAllItems();
                pnl_SeleccCampos.setEnabled(false);
                lbl_SeleccCampos.setEnabled(false);
                lbl_SeleccionCampos.setEnabled(false);
                lbl_SeleccionCampos2.setText("-");
                lbl_SeleccionCampos2.setEnabled(false);
                cbo_Campos.setEnabled(false);
                //
                pnl_IngresarDatos.setEnabled(false);
                lbl_IngresarVCampo.setEnabled(false);
                lbl_IngresarVCampo.setText(">Ingrese el valor del campo para localizar registro a eliminar:");
                txtf_VCampoSelecc.setEnabled(false);
                txtf_VCampoSelecc.setText("");
                btn_ELIMINAR.setEnabled(false);
                break;
            case 1:
                //
                pnl_SeleccCampos.setEnabled(true);
                lbl_SeleccCampos.setEnabled(true);
                lbl_SeleccionCampos.setEnabled(true);
                lbl_SeleccionCampos2.setEnabled(true);
                cbo_Campos.setEnabled(true);
                //
                cbo_Campos.removeAllItems();
                //Añadir items de campos de la tabla 'Clientes'
                cbo_Campos.addItem("id_client");
                cbo_Campos.addItem("rfc_client");
                cbo_Campos.addItem("curp_client");
                break;
            case 2:
                //
                pnl_SeleccCampos.setEnabled(true);
                lbl_SeleccCampos.setEnabled(true);
                lbl_SeleccionCampos.setEnabled(true);
                lbl_SeleccionCampos2.setEnabled(true);
                cbo_Campos.setEnabled(true);
                //
                cbo_Campos.removeAllItems();
                //Añadir items de campos de la tabla 'Domicilio'
                cbo_Campos.addItem("id_domicilio");
                break;
            case 3:
                //
                pnl_SeleccCampos.setEnabled(true);
                lbl_SeleccCampos.setEnabled(true);
                lbl_SeleccionCampos.setEnabled(true);
                lbl_SeleccionCampos2.setEnabled(true);
                cbo_Campos.setEnabled(true);
                //
                cbo_Campos.removeAllItems();
                //Añadir items de campos de la tabla 'Automovil'
                cbo_Campos.addItem("nserie_auto");
                break;
            case 4:
                //
                pnl_SeleccCampos.setEnabled(true);
                lbl_SeleccCampos.setEnabled(true);
                lbl_SeleccionCampos.setEnabled(true);
                lbl_SeleccionCampos2.setEnabled(true);
                cbo_Campos.setEnabled(true);
                //
                cbo_Campos.removeAllItems();
                //Añadir items de campos de la tabla 'Servicio'
                cbo_Campos.addItem("id_serv");
                break;
            case 5:
                //
                pnl_SeleccCampos.setEnabled(true);
                lbl_SeleccCampos.setEnabled(true);
                lbl_SeleccionCampos.setEnabled(true);
                lbl_SeleccionCampos2.setEnabled(true);
                cbo_Campos.setEnabled(true);
                //
                cbo_Campos.removeAllItems();
                //Añadir items de campos de la tabla 'Asesor'
                cbo_Campos.addItem("id_asesor");
                cbo_Campos.addItem("email_asesor");
                break;
            default:
                /*
                */
                break;
        }
    }//GEN-LAST:event_cboSeleccTablaActionPerformed

    private void cbo_CamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_CamposActionPerformed
        //
        switch(cboSeleccTabla.getSelectedIndex()){
            case 0:
                //
                break;
            case 1:
                //
                if(cbo_Campos.getSelectedIndex()==0){
                    lbl_SeleccionCampos2.setText("id_client");
                    //
                    pnl_IngresarDatos.setEnabled(true);
                    lbl_IngresarVCampo.setEnabled(true);
                    txtf_VCampoSelecc.setEnabled(true);
                    txtf_VCampoSelecc.setText("");
                    txtf_VCampoSelecc.setDocument(new LengthRestrictedDocument(11));
                    txtf_VCampoSelecc.setToolTipText("Tamaño: 11 dígitos.");
                    btn_ELIMINAR.setEnabled(true);
                    //
                    lbl_IngresarVCampo.setText(">Ingrese el valor del campo para localizar registro a eliminar: ");
                }else if(cbo_Campos.getSelectedIndex()==1){
                    lbl_SeleccionCampos2.setText("rfc_client");
                    //
                    pnl_IngresarDatos.setEnabled(true);
                    lbl_IngresarVCampo.setEnabled(true);
                    txtf_VCampoSelecc.setEnabled(true);
                    txtf_VCampoSelecc.setText("");
                    txtf_VCampoSelecc.setDocument(new LengthRestrictedDocument(12));
                    txtf_VCampoSelecc.setToolTipText("Tamaño: 12 caracteres.");
                    btn_ELIMINAR.setEnabled(true);
                    //
                    lbl_IngresarVCampo.setText(">Ingrese el valor del campo para localizar registro a eliminar: ");
                }else if(cbo_Campos.getSelectedIndex()==2){
                    lbl_SeleccionCampos2.setText("curp_client");
                    //
                    pnl_IngresarDatos.setEnabled(true);
                    lbl_IngresarVCampo.setEnabled(true);
                    txtf_VCampoSelecc.setEnabled(true);
                    txtf_VCampoSelecc.setText("");
                    txtf_VCampoSelecc.setDocument(new LengthRestrictedDocument(18));
                    txtf_VCampoSelecc.setToolTipText("Tamaño: 18 caracteres.");
                    btn_ELIMINAR.setEnabled(true);
                    //
                    lbl_IngresarVCampo.setText(">Ingrese el valor del campo para localizar registro a eliminar: ");
                }
                break;
            case 2:
                //
                if(cbo_Campos.getSelectedIndex()==0){
                    lbl_SeleccionCampos2.setText("id_domicilio");
                    //
                    pnl_IngresarDatos.setEnabled(true);
                    lbl_IngresarVCampo.setEnabled(true);
                    txtf_VCampoSelecc.setEnabled(true);
                    txtf_VCampoSelecc.setText("");
                    txtf_VCampoSelecc.setDocument(new LengthRestrictedDocument(11));
                    txtf_VCampoSelecc.setToolTipText("Tamaño: 11 dígitos.");
                    btn_ELIMINAR.setEnabled(true);
                    //
                    lbl_IngresarVCampo.setText(">Ingrese el valor del campo para localizar registro a eliminar: ");
                }
                break;
            case 3:
                //
                if(cbo_Campos.getSelectedIndex()==0){
                    lbl_SeleccionCampos2.setText("nserie_auto");
                    //
                    pnl_IngresarDatos.setEnabled(true);
                    lbl_IngresarVCampo.setEnabled(true);
                    txtf_VCampoSelecc.setEnabled(true);
                    txtf_VCampoSelecc.setText("");
                    txtf_VCampoSelecc.setDocument(new LengthRestrictedDocument(16));
                    txtf_VCampoSelecc.setToolTipText("Tamaño: 16 dígitos.");
                    btn_ELIMINAR.setEnabled(true);
                    //
                    lbl_IngresarVCampo.setText(">Ingrese el valor del campo para localizar registro a eliminar: ");
                }
                break;
            case 4:
                //
                if(cbo_Campos.getSelectedIndex()==0){
                    lbl_SeleccionCampos2.setText("id_serv");
                    //
                    pnl_IngresarDatos.setEnabled(true);
                    lbl_IngresarVCampo.setEnabled(true);
                    txtf_VCampoSelecc.setEnabled(true);
                    txtf_VCampoSelecc.setText("");
                    txtf_VCampoSelecc.setDocument(new LengthRestrictedDocument(11));
                    txtf_VCampoSelecc.setToolTipText("Tamaño: 11 dígitos.");
                    btn_ELIMINAR.setEnabled(true);
                    //
                    lbl_IngresarVCampo.setText(">Ingrese el valor del campo para localizar registro a eliminar: ");
                }
                break;
            case 5:
                //
                if(cbo_Campos.getSelectedIndex()==0){
                    lbl_SeleccionCampos2.setText("id_asesor");
                    //
                    pnl_IngresarDatos.setEnabled(true);
                    lbl_IngresarVCampo.setEnabled(true);
                    txtf_VCampoSelecc.setEnabled(true);
                    txtf_VCampoSelecc.setText("");
                    txtf_VCampoSelecc.setDocument(new LengthRestrictedDocument(8));
                    txtf_VCampoSelecc.setToolTipText("Tamaño: 8 dígitos.");
                    btn_ELIMINAR.setEnabled(true);
                    //
                    lbl_IngresarVCampo.setText(">Ingrese el valor del campo para localizar registro a eliminar: ");
                }else if(cbo_Campos.getSelectedIndex()==1){
                    lbl_SeleccionCampos2.setText("email_asesor");
                    //
                    pnl_IngresarDatos.setEnabled(true);
                    lbl_IngresarVCampo.setEnabled(true);
                    txtf_VCampoSelecc.setEnabled(true);
                    txtf_VCampoSelecc.setText("");
                    txtf_VCampoSelecc.setDocument(new LengthRestrictedDocument(35));
                    txtf_VCampoSelecc.setToolTipText("Tamaño máximo: 35 dígitos.");
                    btn_ELIMINAR.setEnabled(true);
                    //
                    lbl_IngresarVCampo.setText(">Ingrese el valor del campo para localizar registro a eliminar: ");
                }
                break;
            default:
                break;
        }
    }//GEN-LAST:event_cbo_CamposActionPerformed

    private void txtf_VCampoSeleccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_VCampoSeleccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_VCampoSeleccActionPerformed

    //MÉTODOS DE ELIMINACIÓN
    //Cliente
    public void eliminarCliente(BeanClient bcli){
        try{
            //PS's
            PreparedStatement prst=con.prepareStatement("DELETE FROM cliente WHERE id_client = ?");
            PreparedStatement prst__=con.prepareStatement("DELETE FROM contratacion WHERE id_client = ?");
            PreparedStatement prst___=con.prepareStatement("DELETE FROM compra WHERE id_client = ?");
            //
            prst.setLong(1, bcli.getId_client());
            prst__.setLong(1, bcli.getId_client());
            prst___.setLong(1, bcli.getId_client());
            //
            int aff_rows3=prst___.executeUpdate();
            int aff_rows2=prst__.executeUpdate();
            int aff_rows=prst.executeUpdate();
            JOptionPane.showMessageDialog(this, "¡Operación exitosa en 'Cliente'!, filas afectadas:"+aff_rows+"\n"+""
                    + "¡Operación exitosa en 'Contratacion'!, filas afectadas:"+aff_rows2+"\n"+""
                    + "¡Operación exitosa en 'Compra'!, filas afectadas:"+aff_rows3, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLException sqle){
            JOptionPane.showMessageDialog(this, "Ha ocurrido una excepción: "+sqle.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    public void eliminarCliente2(BeanClient bcli2){
        //Variables
        ResultSet rs;
        Statement stm;
        String sentenciaSQL = "SELECT id_client FROM cliente WHERE rfc_client = '"+bcli2.getRfc_client()+"'";
        long id_client=0;
        //
        try{
            stm=con.createStatement();
            rs=stm.executeQuery(sentenciaSQL);
            while(rs.next()){
                id_client=rs.getLong(1);
            }
            //PS's
            PreparedStatement prst1=con.prepareStatement("DELETE FROM cliente WHERE rfc_client = ?");
            PreparedStatement prst1__=con.prepareStatement("DELETE FROM contratacion WHERE id_client = ?");
            PreparedStatement prst1___=con.prepareStatement("DELETE FROM compra WHERE id_client = ?");
            
            prst1.setString(1, bcli2.getRfc_client());
            prst1__.setLong(1, id_client);
            prst1___.setLong(1, id_client);
            
            int aff_rows13=prst1___.executeUpdate();
            int aff_rows12=prst1__.executeUpdate();
            int aff_rows1=prst1.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "¡Operación exitosa en 'Cliente'!, filas afectadas:"+aff_rows1+"\n"+""
                    + "¡Operación exitosa en 'Contratacion'!, filas afectadas:"+aff_rows12+"\n"+""
                    + "¡Operación exitosa en 'Compra'!, filas afectadas:"+aff_rows13, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLException sqle1){
            JOptionPane.showMessageDialog(this, "Ha ocurrido una excepción: "+sqle1.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    public void eliminarCliente3(BeanClient bcli3){
        //Variables
        ResultSet rs;
        Statement stm;
        String sentenciaSQL = "SELECT id_client FROM cliente WHERE curp_client = '"+bcli3.getCurp_client()+"'";
        long id_client=0;
        try{
            stm=con.createStatement();
            rs=stm.executeQuery(sentenciaSQL);
            while(rs.next()){
                id_client=rs.getLong(1);
            }
            //PS's
            PreparedStatement prst11=con.prepareStatement("DELETE FROM cliente WHERE curp_client = ?");
            PreparedStatement prst11__=con.prepareStatement("DELETE FROM contratacion WHERE id_client = ?");
            PreparedStatement prst11___=con.prepareStatement("DELETE FROM compra WHERE id_client = ?");
            
            prst11.setString(1, bcli3.getCurp_client());
            prst11__.setLong(1, id_client);
            prst11___.setLong(1, id_client);
            
            int aff_rows113=prst11___.executeUpdate();
            int aff_rows112=prst11__.executeUpdate();
            int aff_rows11=prst11.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "¡Operación exitosa en 'Cliente'!, filas afectadas:"+aff_rows11+"\n"+""
                    + "¡Operación exitosa en 'Contratacion'!, filas afectadas:"+aff_rows112+"\n"+""
                    + "¡Operación exitosa en 'Compra'!, filas afectadas:"+aff_rows113, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLException sqle11){
            JOptionPane.showMessageDialog(this, "Ha ocurrido una excepción: "+sqle11.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    //Domicilio
    public void eliminarDomicilio(BeanDomicilio bdom){
        try{
            PreparedStatement prst2=con.prepareStatement("DELETE FROM domicilio WHERE id_domicilio = ?");
            PreparedStatement prst2__=con.prepareStatement("DELETE FROM cliente WHERE id_domicilio = ?");
            
            prst2.setLong(1, bdom.getId_domicilio());
            prst2__.setLong(1, bdom.getId_domicilio());
            
            int aff_rows22=prst2__.executeUpdate();
            int aff_rows2=prst2.executeUpdate();
            JOptionPane.showMessageDialog(this, "¡Operación exitosa en 'Domicilio'!, filas afectadas:"+aff_rows2+"\n"+""
                    + "¡Operación exitosa en 'Cliente'!, filas afectadas:"+aff_rows22, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLException sqle2){
            JOptionPane.showMessageDialog(this, "Ha ocurrido una excepción: "+sqle2.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    //Automóvil
    public void eliminarAuto(BeanAuto baut){
        try{
            PreparedStatement prst3=con.prepareStatement("DELETE FROM automovil WHERE nserie_auto = ?");
            PreparedStatement prst3_=con.prepareStatement("DELETE FROM compra WHERE nserie_auto = ?");
            PreparedStatement prst3__=con.prepareStatement("DELETE FROM contratacion WHERE nserie_auto = ?");
            
            prst3.setLong(1, baut.getNserie_auto());
            prst3_.setLong(1, baut.getNserie_auto());
            prst3__.setLong(1, baut.getNserie_auto());
            
            int aff_rows33=prst3__.executeUpdate();
            int aff_rows32=prst3_.executeUpdate();
            int aff_rows3=prst3.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "¡Operación exitosa en 'Automovil'!, filas afectadas:"+aff_rows3+"\n"+""
                    + "¡Operación exitosa en 'Compra'!, filas afectadas:"+aff_rows32+"\n"+""
                    + "¡Operación exitosa en 'Contratacion'!, filas afectadas:"+aff_rows33, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLException sqle3){
            JOptionPane.showMessageDialog(this, "Ha ocurrido una excepción: "+sqle3.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    //Servicio
    public void eliminarServicio(BeanServ bserv){
        try{
            PreparedStatement prst4=con.prepareStatement("DELETE FROM servicio WHERE id_serv = ?");
            PreparedStatement prst4_=con.prepareStatement("DELETE FROM contratacion WHERE id_serv = ?");
            
            prst4.setLong(1, bserv.getId_serv());
            prst4_.setLong(1, bserv.getId_serv());
            
            int aff_rows42=prst4_.executeUpdate();
            int aff_rows4=prst4.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "¡Operación exitosa en 'Servicio'!, filas afectadas:"+aff_rows4+"\n"+""
                    + "¡Operación exitosa en 'Contratacion'!, filas afectadas:"+aff_rows42, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLException sqle4){
            JOptionPane.showMessageDialog(this, "Ha ocurrido una excepción: "+sqle4.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    //Asesor
    public void eliminarAsesor(BeanAsesor bases){
        try{
            PreparedStatement prst5=con.prepareStatement("DELETE FROM asesor WHERE id_asesor = ?");
            PreparedStatement prst5_=con.prepareStatement("DELETE FROM compra WHERE id_asesor = ?");
            
            prst5.setInt(1, bases.getId_asesor());
            prst5_.setInt(1, bases.getId_asesor());
            
            int aff_rows52=prst5_.executeUpdate();
            int aff_rows5=prst5.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "¡Operación exitosa en 'Asesor'!, filas afectadas:"+aff_rows5+"\n"+""
                    + "¡Operación exitosa en 'Compra'!, filas afectadas:"+aff_rows52, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLException sqle5){
            JOptionPane.showMessageDialog(this, "Ha ocurrido una excepción: "+sqle5.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    public void eliminarAsesor2(BeanAsesor bases2){
        //Variables
        ResultSet rs;
        Statement stm;
        String sentenciaSQL = "SELECT id_asesor FROM asesor WHERE email_asesor = '"+bases2.getEmail_asesor()+"'";
        int id_asesor=0;
        try{
            stm=con.createStatement();
            rs=stm.executeQuery(sentenciaSQL);
            while(rs.next()){
                id_asesor=rs.getInt(1);
            }
            //PS's
            PreparedStatement prst55=con.prepareStatement("DELETE FROM asesor WHERE email_asesor = ?");
            PreparedStatement prst55_=con.prepareStatement("DELETE FROM compra WHERE id_asesor = ?");
            
            prst55.setString(1, bases2.getEmail_asesor());
            prst55_.setInt(1, id_asesor);
               
            int aff_rows552=prst55_.executeUpdate();
            int aff_rows55=prst55.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "¡Operación exitosa en 'Asesor'!, filas afectadas:"+aff_rows55+"\n"+""
                    + "¡Operación exitosa en 'Compra'!, filas afectadas:"+aff_rows552, "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLException sqle55){
            JOptionPane.showMessageDialog(this, "Ha ocurrido una excepción: "+sqle55.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    } 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaDELETE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaDELETE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaDELETE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaDELETE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaDELETE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ELIMINAR;
    private javax.swing.JComboBox<String> cboSeleccTabla;
    private javax.swing.JComboBox<String> cbo_Campos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Background;
    private javax.swing.JLabel lbl_IngresarVCampo;
    private javax.swing.JLabel lbl_SeleccCampos;
    private javax.swing.JLabel lbl_SeleccTabla;
    private javax.swing.JLabel lbl_SeleccionCampos;
    private javax.swing.JLabel lbl_SeleccionCampos2;
    private javax.swing.JPanel pnl_IngresarDatos;
    private javax.swing.JPanel pnl_SeleccCampos;
    private javax.swing.JTextField txtf_VCampoSelecc;
    // End of variables declaration//GEN-END:variables
}
