/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frames;

//Imports
import javax.swing.ImageIcon;

/**
 *
 * @author Propietario
 */
public class VentanaPrincipal extends javax.swing.JFrame{

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() { 
        initComponents();
        //Icono de la ventana
        ImageIcon icon=new ImageIcon("C:\\Users\\Propietario\\Desktop\\Trabajos - Semestre 8\\Gestión de Proyectos de Software\\NBP\\Sistema de operaciones CRUD CAASA\\src\\Imagenes\\lcaasa.jpg");
        this.setIconImage(icon.getImage());    
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Insert = new javax.swing.JButton();
        btn_Select = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        lbl_Bienvenido = new javax.swing.JLabel();
        lbl_SelectTab = new javax.swing.JLabel();
        lbl_C = new javax.swing.JLabel();
        lbl_R = new javax.swing.JLabel();
        lbl_U = new javax.swing.JLabel();
        lbl_D = new javax.swing.JLabel();
        lbl_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD - Base de Datos CAASA");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Insert.setBackground(new java.awt.Color(255, 51, 51));
        btn_Insert.setFont(new java.awt.Font("Impact", 0, 21)); // NOI18N
        btn_Insert.setText("CREATE");
        btn_Insert.setToolTipText("Inserte un registro en una tabla.");
        btn_Insert.setBorder(null);
        btn_Insert.setFocusPainted(false);
        btn_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InsertActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 140, 40));

        btn_Select.setFont(new java.awt.Font("Impact", 0, 21)); // NOI18N
        btn_Select.setText("READ");
        btn_Select.setToolTipText("Consulte registros de una tabla.");
        btn_Select.setBorder(null);
        btn_Select.setFocusPainted(false);
        btn_Select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SelectActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Select, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 140, 40));

        btn_Update.setBackground(new java.awt.Color(255, 51, 51));
        btn_Update.setFont(new java.awt.Font("Impact", 0, 21)); // NOI18N
        btn_Update.setText("UPDATE");
        btn_Update.setToolTipText("Modifique registros de una tabla.");
        btn_Update.setBorder(null);
        btn_Update.setFocusPainted(false);
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 140, 40));

        btn_Delete.setFont(new java.awt.Font("Impact", 0, 21)); // NOI18N
        btn_Delete.setText("DELETE");
        btn_Delete.setToolTipText("Elimine registros de una tabla.");
        btn_Delete.setBorder(null);
        btn_Delete.setFocusPainted(false);
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 420, 140, 40));

        lbl_Bienvenido.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        lbl_Bienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Bienvenido.setText("¡Bienvenido(a)!");
        jPanel1.add(lbl_Bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 250, 40));

        lbl_SelectTab.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        lbl_SelectTab.setForeground(new java.awt.Color(102, 0, 0));
        lbl_SelectTab.setText("•Seleccione la operación que desea realizar:");
        jPanel1.add(lbl_SelectTab, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        lbl_C.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_C.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/C.png"))); // NOI18N
        jPanel1.add(lbl_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 220, 220));

        lbl_R.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_R.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/R.png"))); // NOI18N
        jPanel1.add(lbl_R, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 220, 220));

        lbl_U.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_U.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/U.png"))); // NOI18N
        jPanel1.add(lbl_U, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 220, 220));

        lbl_D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/D.png"))); // NOI18N
        jPanel1.add(lbl_D, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 220, 220));

        lbl_fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bck.png"))); // NOI18N
        jPanel1.add(lbl_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1045, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InsertActionPerformed
        // 
        VentanaINSERT v_insert=new VentanaINSERT();
        v_insert.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_InsertActionPerformed

    private void btn_SelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SelectActionPerformed
        // 
        VentanaSELECT v_select=new VentanaSELECT();
        v_select.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_SelectActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        //
        VentanaUPDATE v_update=new VentanaUPDATE();
        v_update.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        //
        VentanaDELETE v_delete=new VentanaDELETE();
        v_delete.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Insert;
    private javax.swing.JButton btn_Select;
    private javax.swing.JButton btn_Update;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Bienvenido;
    private javax.swing.JLabel lbl_C;
    private javax.swing.JLabel lbl_D;
    private javax.swing.JLabel lbl_R;
    private javax.swing.JLabel lbl_SelectTab;
    private javax.swing.JLabel lbl_U;
    private javax.swing.JLabel lbl_fondo;
    // End of variables declaration//GEN-END:variables
}
